- name: "Uninstall Mirror Appliance"
  gather_facts: yes
  hosts: all
  tags:
    - quay
  tasks:

    - name: Stop Quay service
      systemd:
        name: quay-app.service
        enabled: no
        daemon_reload: yes
        state: stopped
        force: yes
        scope: user

    - name: Stop Redis service
      systemd:
        name: quay-redis.service
        enabled: no
        daemon_reload: yes
        state: stopped
        force: yes
        scope: user

    - name: Stop Postgres service
      systemd:
        name: quay-postgres.service
        enabled: no
        daemon_reload: yes
        state: stopped
        force: yes
        scope: user

    - name: Stop Quay Pod service
      systemd:
        name: quay-pod.service
        enabled: no
        daemon_reload: yes
        state: stopped
        force: yes
        scope: user

    - name: Delete pod
      containers.podman.podman_pod:
        name: quay-pod
        state: absent

    - name: Create Quay Storage named volume
      containers.podman.podman_volume:
          state: absent
          name: quay-storage
      when: auto_approve|bool == true and quay_storage == "pg-storage"

    - name: Delete Postgres Storage named volume
      containers.podman.podman_volume:
          state: absent
          name: pg-storage
      when: auto_approve|bool == true and pg_storage == "pg-storage"

    - name: Delete necessary directory for Quay local storage
      ansible.builtin.file:
        path: "{{ quay_storage }}"
        state: absent
      become: yes
      when: auto_approve|bool == true and quay_storage.startswith('/')

    - name: Delete necessary directory for Postgres persistent data
      ansible.builtin.file:
        path: "{{ pg_storage }}"
        state: absent
      become: yes
      when: auto_approve|bool == true and pg_storage.startswith('/')

    - name: Delete Install Directory
      file:
        state: absent
        path: "{{ quay_root }}"
      when: auto_approve|bool == true

    - name: Cleanup systemd unit files
      file:
        state: absent
        path: "$HOME/.config/systemd/user/{{ item }}"
      loop:
        - quay-pod.service
        - quay-postgres.service
        - quay-redis.service
        - quay-app.service

    - name: Just force systemd to reread configs (2.4 and above)
      ansible.builtin.systemd:
        daemon_reload: yes
        scope: user
