# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora36"
  config.vm.box_architecture = "amd64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "max"
    qe.smp = "cpus=4,sockets=1,cores=4,threads=1"
    qe.memory = "3072"
    qe.net_device = "virtio-net-pci"
    qe.extra_qemu_args = %w(-accel tcg,thread=multi,tb-size=512)
    qe.forward_port("guestssh", 22, 50021, auto: true)
  end
  config.vm.provision "shell", inline: <<-SHELL
    set -x

    # On macOS with qemu, the systemd-resolved does not work properly. To work
    # around this issue, we disable the systemd-resolved and use Google's DNS.
    systemctl stop systemd-resolved
    systemctl disable systemd-resolved
    rm -f /etc/resolv.conf
    echo "nameserver 8.8.8.8" >/etc/resolv.conf

    dnf install -y \
      acl \
      openssl \
      podman
  SHELL
end
