# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/fedora37"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
  end
  config.vm.provision "shell", inline: <<-SHELL
    dnf install -y \
      acl \
      openssl \
      podman
  SHELL
end
