codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "20...100"

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

ignore:
  - "vendor/**"
  - "test/**"
  - "agent_docs/**"
  - "ansible-runner/**"

flags:
  unit-tests:
    carryforward: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
