- name: Install Redis Service
  hosts: redis
  become: yes
  tasks:
    - name: Copy Redis systemd service file
      template: src=../templates/redis.service dest=/etc/systemd/system/quay-redis.service

    - name: Pull Postgres image
      containers.podman.podman_image:
        name: docker.io/centos/redis-5-centos8

    - name: Start Redis service
      systemd:
        name: quay-redis.service
        enabled: yes
        daemon_reload: yes
        state: started
