- name: Copy Quay Pod systemd service file
  template:
    src: ../templates/pod.service.j2
    dest: $HOME/.config/systemd/user/quay-pod.service

- name: Check if pod pause image is loaded
  command: podman inspect --type=image {{ pause_image }}
  register: r
  ignore_errors: yes

- name: Pull Infra image
  containers.podman.podman_image:
    name: "{{ pause_image }}"
  when: r.rc != 0
  retries: 5
  delay: 5

- name: Start Quay Pod service
  systemd:
    name: quay-pod.service
    enabled: yes
    daemon_reload: yes
    state: restarted
    scope: user
