- name: Copy Postgres systemd service file
  template:
    src: ../templates/postgres.service.j2
    dest: /etc/systemd/system/quay-postgres.service

- name: Check if Postgres image is loaded
  command: podman inspect --type=image {{ postgres_image }}
  register: pg
  ignore_errors: yes

- name: Pull Postgres image
  containers.podman.podman_image:
    name: "{{ postgres_image }}"
  when: pg.rc != 0
  retries: 5
  delay: 5

- name: Start Postgres service
  systemd:
    name: quay-postgres.service
    enabled: yes
    daemon_reload: yes
    state: restarted
