---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-20-early-access/ee-minimal-rhel8

dependencies:
  galaxy: requirements.yml

additional_build_steps:
  append:
    - COPY app /runner
